name: Déploiement en recette

on:
  push:
    branches: [recette]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: 47ng/actions-clever-cloud@v2.0.0
      with:
        appID: ${{ secrets.CLEVER_APP_API_RECETTE_ID }}
        force: true
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
    # - uses: actions/checkout@v4
    # - name: Create Sentry release
    #   uses: getsentry/action-release@v1
    #   env:
    #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_BETA_AUTH_TOKEN }}
    #     SENTRY_ORG: ${{ secrets.SENTRY_BETA_ORG }}
    #     SENTRY_PROJECT: ${{ secrets.SENTRY_API_PROJECT }}
    #     SENTRY_URL: ${{ secrets.SENTRY_BETA_URL }}
    #   with:
    #     environment: recette
    #     ignore_missing: true
    #     ignore_empty: true
