# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Déploiement en recette

on:
  push:
    branches: [ recette ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - uses: 47ng/actions-clever-cloud@v1.2.0
      with:
        appID: ${{ secrets.CLEVER_APP_API_RECETTE_ID }}
        timeout: 300 #5 minutes before move on (in case of never exit even though a deployment is successful)
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
    - uses: actions/checkout@v2
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_BETA_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_BETA_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_API_PROJECT }}
        SENTRY_URL: ${{ secrets.SENTRY_BETA_URL }}
      with:
        environment: recette
        ignore_missing: true
        ignore_empty: true
