name: Déploiement en production

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow

    - uses: 47ng/actions-clever-cloud@v1.2.0
      with:
        appID: ${{ secrets.CLEVER_APP_API_PRODUCTION_ID }}
        timeout: 300 #5 minutes before move on (in case of never exit even though a deployment is successful)
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
    - uses: actions/checkout@v4
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_BETA_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_BETA_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_API_PROJECT }}
        SENTRY_URL: ${{ secrets.SENTRY_BETA_URL }}
      with:
        environment: production
        ignore_missing: true
        ignore_empty: true
