name: ESLint

on:
  push:
    branches: [ main, recette ]
  pull_request:
    branches: [ main, recette ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Install modules
      run: npm i
    - name: Lint
      run: npm run lint
